// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fish/finder/proto/Message.proto

package fish.finder.proto;

public final class Message {
  private Message() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public enum MessageType
      implements com.google.protobuf.ProtocolMessageEnum {
    PING(0, 0),
    PONG(1, 1),
    SEARCH(2, 2),
    RESULTS(3, 3),
    TRANSFER(4, 4),
    ;
    
    public static final int PING_VALUE = 0;
    public static final int PONG_VALUE = 1;
    public static final int SEARCH_VALUE = 2;
    public static final int RESULTS_VALUE = 3;
    public static final int TRANSFER_VALUE = 4;
    
    
    public final int getNumber() { return value; }
    
    public static MessageType valueOf(int value) {
      switch (value) {
        case 0: return PING;
        case 1: return PONG;
        case 2: return SEARCH;
        case 3: return RESULTS;
        case 4: return TRANSFER;
        default: return null;
      }
    }
    
    public static com.google.protobuf.Internal.EnumLiteMap<MessageType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<MessageType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<MessageType>() {
            public MessageType findValueByNumber(int number) {
              return MessageType.valueOf(number);
            }
          };
    
    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return fish.finder.proto.Message.getDescriptor().getEnumTypes().get(0);
    }
    
    private static final MessageType[] VALUES = {
      PING, PONG, SEARCH, RESULTS, TRANSFER, 
    };
    
    public static MessageType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }
    
    private final int index;
    private final int value;
    
    private MessageType(int index, int value) {
      this.index = index;
      this.value = value;
    }
    
    // @@protoc_insertion_point(enum_scope:MessageType)
  }
  
  public interface RequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int32 ttl = 1;
    boolean hasTtl();
    int getTtl();
    
    // required .MessageType type = 4;
    boolean hasType();
    fish.finder.proto.Message.MessageType getType();
    
    // required fixed64 source = 2;
    boolean hasSource();
    long getSource();
    
    // optional fixed64 destination = 3;
    boolean hasDestination();
    long getDestination();
    
    // optional string data = 5;
    boolean hasData();
    String getData();
  }
  public static final class Request extends
      com.google.protobuf.GeneratedMessage
      implements RequestOrBuilder {
    // Use Request.newBuilder() to construct.
    private Request(Builder builder) {
      super(builder);
    }
    private Request(boolean noInit) {}
    
    private static final Request defaultInstance;
    public static Request getDefaultInstance() {
      return defaultInstance;
    }
    
    public Request getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return fish.finder.proto.Message.internal_static_Request_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return fish.finder.proto.Message.internal_static_Request_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required int32 ttl = 1;
    public static final int TTL_FIELD_NUMBER = 1;
    private int ttl_;
    public boolean hasTtl() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getTtl() {
      return ttl_;
    }
    
    // required .MessageType type = 4;
    public static final int TYPE_FIELD_NUMBER = 4;
    private fish.finder.proto.Message.MessageType type_;
    public boolean hasType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public fish.finder.proto.Message.MessageType getType() {
      return type_;
    }
    
    // required fixed64 source = 2;
    public static final int SOURCE_FIELD_NUMBER = 2;
    private long source_;
    public boolean hasSource() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public long getSource() {
      return source_;
    }
    
    // optional fixed64 destination = 3;
    public static final int DESTINATION_FIELD_NUMBER = 3;
    private long destination_;
    public boolean hasDestination() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public long getDestination() {
      return destination_;
    }
    
    // optional string data = 5;
    public static final int DATA_FIELD_NUMBER = 5;
    private java.lang.Object data_;
    public boolean hasData() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public String getData() {
      java.lang.Object ref = data_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          data_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getDataBytes() {
      java.lang.Object ref = data_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        data_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      ttl_ = 0;
      type_ = fish.finder.proto.Message.MessageType.PING;
      source_ = 0L;
      destination_ = 0L;
      data_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasTtl()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSource()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, ttl_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeFixed64(2, source_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeFixed64(3, destination_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(4, type_.getNumber());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getDataBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, ttl_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed64Size(2, source_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed64Size(3, destination_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, type_.getNumber());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getDataBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static fish.finder.proto.Message.Request parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static fish.finder.proto.Message.Request parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static fish.finder.proto.Message.Request parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static fish.finder.proto.Message.Request parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static fish.finder.proto.Message.Request parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static fish.finder.proto.Message.Request parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static fish.finder.proto.Message.Request parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static fish.finder.proto.Message.Request parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static fish.finder.proto.Message.Request parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static fish.finder.proto.Message.Request parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(fish.finder.proto.Message.Request prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements fish.finder.proto.Message.RequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return fish.finder.proto.Message.internal_static_Request_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return fish.finder.proto.Message.internal_static_Request_fieldAccessorTable;
      }
      
      // Construct using fish.finder.proto.Message.Request.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        ttl_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = fish.finder.proto.Message.MessageType.PING;
        bitField0_ = (bitField0_ & ~0x00000002);
        source_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        destination_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000008);
        data_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return fish.finder.proto.Message.Request.getDescriptor();
      }
      
      public fish.finder.proto.Message.Request getDefaultInstanceForType() {
        return fish.finder.proto.Message.Request.getDefaultInstance();
      }
      
      public fish.finder.proto.Message.Request build() {
        fish.finder.proto.Message.Request result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private fish.finder.proto.Message.Request buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        fish.finder.proto.Message.Request result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public fish.finder.proto.Message.Request buildPartial() {
        fish.finder.proto.Message.Request result = new fish.finder.proto.Message.Request(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.ttl_ = ttl_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.source_ = source_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.destination_ = destination_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.data_ = data_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof fish.finder.proto.Message.Request) {
          return mergeFrom((fish.finder.proto.Message.Request)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(fish.finder.proto.Message.Request other) {
        if (other == fish.finder.proto.Message.Request.getDefaultInstance()) return this;
        if (other.hasTtl()) {
          setTtl(other.getTtl());
        }
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasSource()) {
          setSource(other.getSource());
        }
        if (other.hasDestination()) {
          setDestination(other.getDestination());
        }
        if (other.hasData()) {
          setData(other.getData());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasTtl()) {
          
          return false;
        }
        if (!hasType()) {
          
          return false;
        }
        if (!hasSource()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              ttl_ = input.readInt32();
              break;
            }
            case 17: {
              bitField0_ |= 0x00000004;
              source_ = input.readFixed64();
              break;
            }
            case 25: {
              bitField0_ |= 0x00000008;
              destination_ = input.readFixed64();
              break;
            }
            case 32: {
              int rawValue = input.readEnum();
              fish.finder.proto.Message.MessageType value = fish.finder.proto.Message.MessageType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(4, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                type_ = value;
              }
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              data_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int32 ttl = 1;
      private int ttl_ ;
      public boolean hasTtl() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getTtl() {
        return ttl_;
      }
      public Builder setTtl(int value) {
        bitField0_ |= 0x00000001;
        ttl_ = value;
        onChanged();
        return this;
      }
      public Builder clearTtl() {
        bitField0_ = (bitField0_ & ~0x00000001);
        ttl_ = 0;
        onChanged();
        return this;
      }
      
      // required .MessageType type = 4;
      private fish.finder.proto.Message.MessageType type_ = fish.finder.proto.Message.MessageType.PING;
      public boolean hasType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public fish.finder.proto.Message.MessageType getType() {
        return type_;
      }
      public Builder setType(fish.finder.proto.Message.MessageType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        type_ = value;
        onChanged();
        return this;
      }
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        type_ = fish.finder.proto.Message.MessageType.PING;
        onChanged();
        return this;
      }
      
      // required fixed64 source = 2;
      private long source_ ;
      public boolean hasSource() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public long getSource() {
        return source_;
      }
      public Builder setSource(long value) {
        bitField0_ |= 0x00000004;
        source_ = value;
        onChanged();
        return this;
      }
      public Builder clearSource() {
        bitField0_ = (bitField0_ & ~0x00000004);
        source_ = 0L;
        onChanged();
        return this;
      }
      
      // optional fixed64 destination = 3;
      private long destination_ ;
      public boolean hasDestination() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public long getDestination() {
        return destination_;
      }
      public Builder setDestination(long value) {
        bitField0_ |= 0x00000008;
        destination_ = value;
        onChanged();
        return this;
      }
      public Builder clearDestination() {
        bitField0_ = (bitField0_ & ~0x00000008);
        destination_ = 0L;
        onChanged();
        return this;
      }
      
      // optional string data = 5;
      private java.lang.Object data_ = "";
      public boolean hasData() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public String getData() {
        java.lang.Object ref = data_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          data_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setData(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        data_ = value;
        onChanged();
        return this;
      }
      public Builder clearData() {
        bitField0_ = (bitField0_ & ~0x00000010);
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }
      void setData(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000010;
        data_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:Request)
    }
    
    static {
      defaultInstance = new Request(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:Request)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Request_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Request_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\037fish/finder/proto/Message.proto\"e\n\007Req" +
      "uest\022\013\n\003ttl\030\001 \002(\005\022\032\n\004type\030\004 \002(\0162\014.Messag" +
      "eType\022\016\n\006source\030\002 \002(\006\022\023\n\013destination\030\003 \001" +
      "(\006\022\014\n\004data\030\005 \001(\t*H\n\013MessageType\022\010\n\004PING\020" +
      "\000\022\010\n\004PONG\020\001\022\n\n\006SEARCH\020\002\022\013\n\007RESULTS\020\003\022\014\n\010" +
      "TRANSFER\020\004B\023\n\021fish.finder.proto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_Request_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_Request_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Request_descriptor,
              new java.lang.String[] { "Ttl", "Type", "Source", "Destination", "Data", },
              fish.finder.proto.Message.Request.class,
              fish.finder.proto.Message.Request.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
